// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yxoitmxgrgnzbwkjbgbg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4b2l0bXhncmduemJ3a2piZ2JnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3ODI4NjAsImV4cCI6MjA2MDM1ODg2MH0.O8TYztQmcNmoZWY9fz6rRgUMNCRWk-_fwchBwQUVj2A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);